steps:
  # Step 1: Initialize Terraform
  - name: "hashicorp/terraform:light"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        terraform init

  # Step 2: Run Terraform Plan
  - name: "hashicorp/terraform:light"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        terraform plan -out=tfplan

  # Step 3: Apply the Terraform Plan
  - name: "hashicorp/terraform:light"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        terraform apply -input=false tfplan


#cloud-build-logs-bucket01
# Set the logging bucket
logsBucket: "gs://cloud-build-logs-bucket01"

# Set the build timeout (optional)
timeout: "1200s"
